const addOneDepartmentClearanceRequirementRecord = require('./addOneDepartmentClearanceRequirementRecord')

module.exports.addOneDepartmentClearanceRequirementRecord = addOneDepartmentClearanceRequirementRecord